POST http://localhost:3000/times HTTP/1.1
Content-Type: application/json

{
    "nome": "The Last Dance",
    "descricao": "Um time topado de CS-GO"
}

###

GET http://localhost:3000/times HTTP/1.1
Content-Type: application/json

##

GET http://localhost:3000/times/2 HTTP/1.1
Content-Type: application/json

### 

POST http://localhost:3000/times/1/membros HTTP/1.1
Content-Type: application/json

{
    "nome": "Fernando",
    "sobrenome": "Alvarenga",
    "nickname": "Fer",
    "funcao": "Jogador"
}